### ISSUE TITLE
Creating a Contact Us page

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#10]
We need an contact us page for our website. Is anyone willing to do just comment below. this issue was opened for first time contributors. Also experinced one can also make PR for this. I'll try to provide you the UI for this

**Comment by willdelorm** [comment]
Hi @MohamedMafaz, I'd be happy to create a contact page for you. Please provide any details about how you'd like it to look.

**Comment by MohamedMafaz** [comment]
![Contact Us Page](https://user-images.githubusercontent.com/113255500/233270159-7ab99565-3cfa-4eb0-8c74-93edf95d4ea7.png)
Hi Willdelorm!
I attached the image and figma file for contact us page UI. Kindly develop the page as same as UI. When submitting PR host your live site in Github and drop me a link. If you have any doubts Don't hesitate to ask me. In Figma file You can get the following things:
1) Font family & Size
2) Colours
3) CSS Properties
4) Downloadable Images

Make sure that the page you developed is responsive. When developing for mobile just remove the image. https://drive.google.com/file/d/1z2iIVfEt_omU9bvaSAhZv6nR4Iav-6xu/view?usp=sharing

**Comment by MohamedMafaz** [comment]
Name your html file as contactus.html and css file as contactus.css

**Comment by MohamedMafaz** [comment]
Congratulations on your outstanding contribution to GitHub! Your dedication and hard work towards open-source is truly inspiring. I have no doubt that with your skills and passion, you will continue to reach new heights in the world of open-source. Best of luck for your future endeavors!
