### ISSUE TITLE
Need to add Loading Animation

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#11]
In our website we need to add a good loading animation. If anyone willing to do just comment below. and I'll assign you for this issue

**Comment by KelvinHoky** [comment]
Im interested. Assign me 😃

**Comment by MohamedMafaz** [comment]
You were assigned to this issue. Good Luck 👍. Kindly give me the live link which is hosted in GitHub Page when you submit your PR.

**Comment by KelvinHoky** [comment]
Can you give me more details on how you'd like it to look? Do you want it on separate files or integrate it to your css files?

**Comment by MohamedMafaz** [comment]
https://youtu.be/U5iUc8U3coI?t=33 If it looks like this that will be awesome. #4 Making pancake' loader. Background color should be in #FFF0F0 . Instead of Cooking in Progress. mention Loading...

**Comment by KelvinHoky** [comment]
Heyy, Kelvin here ✌Ive done as you've wanted. Since i dont know where you want me to put it, Ive put the loading page in separate files. You can see it here https://kelvinhoky.github.io/Fodome/loading. Be sure to let me know what you think.

**Comment by MohamedMafaz** [comment]
Congratulations on your outstanding contribution to GitHub! Your dedication and hard work towards open-source is truly inspiring. I have no doubt that with your skills and passion, you will continue to reach new heights in the world of open-source. Best of luck for your future endeavors!

**Comment by KelvinHoky** [comment]
Thank you. I would love to collaborating with you in the future. If you have any upcoming projects or ideas that you think I could contribute to, please don't hesitate to let me know. Once again, thank you for the chance to work on this project.✌
