### ISSUE TITLE
Scrolling Functionality Not Working on Website

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#15]
The issue title "Scrolling Functionality Not Working on Website" indicates that the user is unable to scroll the content of a website, either horizontally or vertically. This problem could occur due to a variety of reasons, including an error in the website's code, an issue with the user's web browser, or an issue with the device being used to access the website. Without the ability to scroll, the user is unable to view the complete content of the website, which can result in a frustrating user experience. This issue needs to be addressed promptly to ensure that users can fully utilize the website's features and functionality.

**Comment by naim16031988** [comment]
can I work on this issue ?

**Comment by MohamedMafaz** [comment]
Sure!

**Comment by naim16031988** [comment]
ok, thank you .i will let you know when i have some result

**Comment by naim16031988** [comment]
I just send a PR 
thnks!

**Comment by MohamedMafaz** [comment]
Congratulations on your outstanding contribution to GitHub! Your dedication and hard work towards open-source is truly inspiring. I have no doubt that with your skills and passion, you will continue to reach new heights in the world of open-source. Best of luck for your future endeavors!
