### ISSUE TITLE
Make the navigation bar responsive on mobile 

### ISSUE THREAD

**Issue by naim16031988** [MohamedMafaz/Fodome#17]
The navbar is not responsive. and we need a mobile design. i am not good in designing but a tried a prototype just for the navigation bar. i am proposing this design and i need somebody to discuss it. 
<img width="529" alt="Screenshot 2023-04-30 230001" src="https://user-images.githubusercontent.com/125624860/235397437-b6033c0a-78df-4d39-b3e6-fcc834895b03.png">
<img width="279" alt="Screenshot 2023-04-30 231317" src="https://user-images.githubusercontent.com/125624860/235397467-92b3477b-782c-413d-a7c0-58b22cc69e6f.png">

**Comment by MohamedMafaz** [comment]
Dear Naim Maouche,

Thank you for bringing up the issue regarding the non-responsive Navbar on Fodome website. I want to inform you that our team is aware of this problem, and one of our contributors, Nuel, is currently working on fixing it.

As such, I have taken the liberty of closing this issue. However, if you encounter any further problems or have any suggestions, please do not hesitate to let us know.

Thank you for your valuable feedback and for your continued support of our project.

Best regards,
Mohamed Mafaz P R
