### ISSUE TITLE
Add email notification for Contact Us form submissions

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#18]
We are currently seeking contributors to help us implement a new feature on our Contact Us page. Specifically, we need to add an email notification that alerts us whenever a user submits a message via the Contact Us form.

This issue is open for contributions, and we welcome any interested developers to participate. You do not need to be assigned to the issue to begin working on it; simply comment on the issue thread indicating that you are taking on the task to avoid multiple contributors working on the same issue.

We appreciate any suggestions and contributions, and look forward to working with the open-source community to enhance our website's functionality.

**Comment by naim16031988** [comment]
Hi Mohamed Mafaz, if we want to do this with JS, we need to sign up to EmailJS account and get a user ID. After signing up, we need to create a new Email Service and Choose the email provider we want to use (such as Gmail, Outlook, or Yahoo), and enter the credentials for the email account we want to use for sending emails.

**Comment by MohamedMafaz** [comment]
Looks like you're all set to make waves with this idea, Naim! You've been assigned to the task, so let's get ready to rock and roll.

**Comment by naim16031988** [comment]
HELLO Mohamed,
I got some results and i wanna share them with you.
so this is the contactus page 
<img width="906" alt="Screenshot 2023-05-03 204148" src="https://user-images.githubusercontent.com/125624860/236082245-c96e828a-5427-43d8-a4cf-b0680d048319.png">
when we hit Send it shows me this 
<img width="911" alt="Screenshot 2023-05-03 204233" src="https://user-images.githubusercontent.com/125624860/236082576-1d31457d-a2db-4fc1-b2f1-73e325f6e700.png">
and I am receiving this Email
<img width="719" alt="Screenshot 2023-05-03 204813" src="https://user-images.githubusercontent.com/125624860/236082761-88da030c-42bd-4b68-804a-74161cd576d0.png">
every things looks good I think . 
I need a service Email from you to link this page to your mailbox otherwise i am gonna receive all those messages

**Comment by MohamedMafaz** [comment]
Can you give me your email? I'll send login credentials to it

**Comment by naim16031988** [comment]
Yes of corse 

Naimmaouche1988@yahoo.com

**Comment by MohamedMafaz** [comment]
login credentials sent. Pls check your email

**Comment by naim16031988** [comment]
Didnt receive yet

**Comment by MohamedMafaz** [comment]
Can you check now

**Comment by naim16031988** [comment]
Ok i got it

**Comment by MohamedMafaz** [comment]
Hi Naim,
Once you add my email Id give me the live link which is hosted in GitHub Page

**Comment by naim16031988** [comment]
Ok

**Comment by naim16031988** [comment]
hello Mohamed,
can you check your email ?
i thimk you need to verfify the adress email. 
i am receiving an error when i try to send you email

**Comment by MohamedMafaz** [comment]
Hey @naim16031988 
I didn't receive any email still now
![Screenshot (129)](https://user-images.githubusercontent.com/113255500/236372447-9dce9da6-87fa-47f7-989e-93ce02dbf65e.png)

**Comment by MohamedMafaz** [comment]
Hi @naim16031988 
Can you take a look at this issue. This is my new project and expecting contributors for some help. https://github.com/MohamedMafaz/Propoplex/issues/1

**Comment by MohamedMafaz** [comment]
Dear valued contributor,

Thank you for your outstanding contribution! Your hard work and dedication have not gone unnoticed, and your commitment to excellence is truly inspiring. Your contributions will be forever engraved in the history of our project.

As a token of appreciation, I would like to extend my blessings to you. May you continue to soar to new heights and touch the very peak of programming. Your talents and expertise are invaluable, and I have no doubt that you will achieve great success in all your future endeavors.

Thank you once again for your exceptional work and for being a valuable member of our team.
