### ISSUE TITLE
Transforming ITC Grand Chola: Redefining Luxury in Our Partnered Hotels Section

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#19]
Our partnered hotels section showcases some of the most luxurious and stunning hotels around the world. However, we've noticed that the ITC Grand Chola hotel doesn't quite match up with the rest of the hotels in terms of visuals. We need to elevate the look of the ITC Grand Chola hotel to ensure that it is just as visually appealing and enticing as the other hotels featured on our website. Our customers deserve to see the true beauty and elegance of this magnificent hotel, and we want to make sure they can do so with ease. So, let's roll up our sleeves and give the ITC Grand Chola the visual makeover it deserves!

**Comment by RWUBAKWANAYO** [comment]
Hi @MohamedMafaz, I'd like to take this issue related to the visual makeover of the ITC Grand Chola hotel in our partnered hotels section. If possible, could you kindly assign me to this issue so that I may begin working on it as soon as possible?

**Comment by MohamedMafaz** [comment]
Congratulations 🎉 You were assigned to this issue. When submitting your PR make sure to give a live link of the website which is hosted in Github Pages

**Comment by MohamedMafaz** [comment]
@RWUBAKWANAYO made an PR on this issue and it was merged. So, this issue was closed
