### ISSUE TITLE
good first issue

### ISSUE THREAD

**Issue by therealtmmy** [MohamedMafaz/Fodome#28]
Repo needs an MIT License to be open source
- Update the readme directing how contributors can clone repo with terminal.
//I will work on every of the issues have raised and commit them.

**Comment by MohamedMafaz** [comment]
Hey @therealtmmy 
I appreciate your spirit for Open source. I have another repo and I am looking for a contributor for this issue. Please take a look at that. You can deploy in any free hoating providing service. https://github.com/MohamedMafaz/Propoplex/issues/11
