### ISSUE TITLE
Want to create navbar.html for integrating navbar

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#30]
Hey Coders!
Hope you're doing great. Our project have an issue and looking for a contributor. As a contributor you need to do following things:
- All the pages have navbar but aren't linked using navbar.html
- You need to create a navbar file and integrate with three pages (Home Page, Login Page, Contact Us Page)

If you're interested on this issue. Just comment **I am working on this**. So that we can avoid multiple contributors working on the same issue. But, for starting work you don't need approval.

Thanks & Regards,
Mohamed Mafaz P R,
Propoplex.

**Comment by malinuuus** [comment]
Hi, I can work on this

**Comment by MohamedMafaz** [comment]
@malinuuus has submitted a PR that closes this issue. Thanks
