### ISSUE TITLE
Navigation bar disappears on scrolling to certain sections

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#5]
Currently, the navigation bar on the Fodome website disappears when scrolling to certain sections, including the "Experience luxury with our partnered hotels" and "Recently Ordered Foods By Our Customers" sections. This issue aims to address this problem, ensuring that the navigation bar remains visible at all times for a better user experience.

The changes required to fix this issue include:

Modifying the website's CSS to ensure that the navigation bar remains fixed at the top of the screen, regardless of the user's scroll position.
Testing the website across different devices and screen sizes to ensure that the navigation bar remains visible and functional on all platforms.
Updating the website's code and documentation to reflect the changes made.
As a note to contributors, please refrain from commenting "Assign me this issue". Instead, you can comment on the issue to let other contributors know that you are working on it, so that they can focus on other issues. Let's collaborate and work together to resolve this issue and enhance the user experience of the Fodome website.

**Comment by notMONGCHAW** [comment]
Is anyone still working on the issue?

Edit -1 : What are the screen sizes that are showing issues

**Comment by MohamedMafaz** [comment]
This issue was assigned to you. Well Done!
![Screenshot (34)](https://user-images.githubusercontent.com/113255500/232468749-84a5450a-1c65-433c-a454-aff5fe3a0c7b.png)

**Comment by MohamedMafaz** [comment]
Hope you understand the issue. If not just comment below

**Comment by MohamedMafaz** [comment]
Is there any updates?

**Comment by BrightTNut** [comment]
hi I think I fixed your issue

**Comment by MohamedMafaz** [comment]
Congradulations!!! BrightTNut Fixed this issue. So, I'll close it
