### ISSUE TITLE
Add a footer section to our project

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#6]
Our project needs a footer section, and we would love for you to be a part of it! This is a great opportunity to showcase your skills and contribute to the community. Don't worry, you don't need permission to start working on this issue. Just comment "I am working on this issue" to let us know you're on it, and we'll avoid having multiple contributors working on the same issue. We have attached the UI for the footer section, so you can focus on creating a great user experience. When submitting your PR, make sure to host it on Github Pages and give us a live site link. Let's work together to make our project even better!

UI Link - https://www.figma.com/proto/yt0SRJZ64exI6Dp89PpvOD/Fodome?node-id=2-2

**Comment by rahulrana701** [comment]
hi @MohamedMafaz I would like to work on this issue , can you assign it to me..

**Comment by MohamedMafaz** [comment]
You were assigned to this issue. When submitting your PR make sure to give a live hosted link(Github Pages)

**Comment by MohamedMafaz** [comment]
Hey @RahulRana701 
I saw that you were opened an PR and closed. May I know what is the reason for it. I sent you this message to confirm that you are not closed it accidentally.

**Comment by MohamedMafaz** [comment]
Hey @RahulRana701 
I saw that you were opened an PR and closed. May I know what is the reason for it. I sent you this message to confirm that you are not closed it accidentally.

**Comment by rahulrana701** [comment]
hi @MohamedMafaz I closed it because there were some conflicts in that pr , so I decided to make a new pr

**Comment by MohamedMafaz** [comment]
Ok no problem

**Comment by rahulrana701** [comment]
@MohamedMafaz do I have to push my changes in the main branch , because when I pushed my changes in some other branch different from main , the pr was having some conflicts..

**Comment by MohamedMafaz** [comment]
Yeah, sure.
