### ISSUE TITLE
Need to create a Login page

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Fodome#8]

**Comment by BrightTNut** [comment]
hi there I love to try

**Comment by MohamedMafaz** [comment]
Okay. Sounds Good!! I'll give you the UI. You can start work after that. But remember it must be responsive.

**Comment by BrightTNut** [comment]
thanks

**Comment by MohamedMafaz** [comment]
Hi BrightTNut,
I don't have time to design the UI for login page. so you can do it yourself. Try to do in glass effect and use some 3d images. Of course, It needs to have email ID & Password section. 
kindly follow background colour and font styles as same as home page

**Comment by MohamedMafaz** [comment]
Write html in file named login.html and css in login.css. So it is easy to navigate. Try to host the forked copy of Fodome in Github Pages. So that it is easy to check.

**Comment by BrightTNut** [comment]
okay I will try

**Comment by MohamedMafaz** [comment]
Try your best

**Comment by MohamedMafaz** [comment]
Can I get your discord id

**Comment by BrightTNut** [comment]
![Screenshot 2023-04-17 191412](https://user-images.githubusercontent.com/118769123/233287669-ecb25bd4-6214-48c6-a9b4-ccce0c148325.png)

**Comment by BrightTNut** [comment]
hi there i have created login page push it
please see it give me feedback
if you like it its my plesure
thank you'

**Comment by MohamedMafaz** [comment]
make a PR

**Comment by MohamedMafaz** [comment]
https://brighttnut.github.io/Fodome/login.html I am satisfied with your contribution. Just make a PR I'll merge it
